// <auto-generated>This is auto-generated code by DIS. Do not modify.</auto-generated>
using System.ComponentModel;
using System.Collections;
using System.Collections.Generic;
using System.Linq;

namespace Skyline.DataMiner.Scripting
{
public static class Parameter
{
	/// <summary>PID: 10 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int status_10 = 10;
	/// <summary>PID: 10 | Type: read</summary>
	public const int status = 10;
	/// <summary>PID: 11 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int currentcompressedbitrateencoder_11 = 11;
	/// <summary>PID: 11 | Type: read</summary>
	public const int currentcompressedbitrateencoder = 11;
	/// <summary>PID: 12 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int autochromaweight_12 = 12;
	/// <summary>PID: 12 | Type: read</summary>
	public const int autochromaweight = 12;
	/// <summary>PID: 13 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int chromaweight_13 = 13;
	/// <summary>PID: 13 | Type: read</summary>
	public const int chromaweight = 13;
	/// <summary>PID: 14 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int losslessmode_14 = 14;
	/// <summary>PID: 14 | Type: read</summary>
	public const int losslessmode = 14;
	/// <summary>PID: 15 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int decoderstatus_15 = 15;
	/// <summary>PID: 15 | Type: read</summary>
	public const int decoderstatus = 15;
	/// <summary>PID: 16 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int currentcompressedbitratedecoder_16 = 16;
	/// <summary>PID: 16 | Type: read</summary>
	public const int currentcompressedbitratedecoder = 16;
	/// <summary>PID: 17 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int progressionorder_17 = 17;
	/// <summary>PID: 17 | Type: read</summary>
	public const int progressionorder = 17;
	/// <summary>PID: 18 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int codeblockwidth_18 = 18;
	/// <summary>PID: 18 | Type: read</summary>
	public const int codeblockwidth = 18;
	/// <summary>PID: 19 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int codeblockheight_19 = 19;
	/// <summary>PID: 19 | Type: read</summary>
	public const int codeblockheight = 19;
	public class Write
	{
		/// <summary>PID: 110 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int status_110 = 110;
		/// <summary>PID: 110 | Type: write</summary>
		public const int status = 110;
		/// <summary>PID: 112 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int autochromaweight_112 = 112;
		/// <summary>PID: 112 | Type: write</summary>
		public const int autochromaweight = 112;
		/// <summary>PID: 113 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int chromaweight_113 = 113;
		/// <summary>PID: 113 | Type: write</summary>
		public const int chromaweight = 113;
		/// <summary>PID: 115 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int decoderstatus_115 = 115;
		/// <summary>PID: 115 | Type: write</summary>
		public const int decoderstatus = 115;
		/// <summary>PID: 117 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int progressionorder_117 = 117;
		/// <summary>PID: 117 | Type: write</summary>
		public const int progressionorder = 117;
	}
}
public class WriteParameters
{
	/// <summary>PID: 110  | Type: write | DISCREETS: N/A = 0, Enabled = 1</summary>
	public System.Object Status {get { return Protocol.GetParameter(110); }set { Protocol.SetParameter(110, value); }}
	/// <summary>PID: 112  | Type: write | DISCREETS: N/A = 0, Enabled = 1</summary>
	public System.Object Autochromaweight {get { return Protocol.GetParameter(112); }set { Protocol.SetParameter(112, value); }}
	/// <summary>PID: 113  | Type: write</summary>
	public System.Object Chromaweight {get { return Protocol.GetParameter(113); }set { Protocol.SetParameter(113, value); }}
	/// <summary>PID: 115  | Type: write | DISCREETS: N/A = 0, Enabled = 1</summary>
	public System.Object Decoderstatus {get { return Protocol.GetParameter(115); }set { Protocol.SetParameter(115, value); }}
	/// <summary>PID: 117  | Type: write | DISCREETS: LCRP = 0, RLCP = 1, RPCL = 2, PCRL = 3, CPRL = 4</summary>
	public System.Object Progressionorder {get { return Protocol.GetParameter(117); }set { Protocol.SetParameter(117, value); }}
	public SLProtocolExt Protocol;
	public WriteParameters(SLProtocolExt protocol)
	{
		Protocol = protocol;
	}
}
public interface SLProtocolExt : SLProtocol
{
	object Afterstartup_dummy { get; set; }
	object Status_10 { get; set; }
	object Status { get; set; }
	object Currentcompressedbitrateencoder_11 { get; set; }
	object Currentcompressedbitrateencoder { get; set; }
	object Autochromaweight_12 { get; set; }
	object Autochromaweight { get; set; }
	object Chromaweight_13 { get; set; }
	object Chromaweight { get; set; }
	object Losslessmode_14 { get; set; }
	object Losslessmode { get; set; }
	object Decoderstatus_15 { get; set; }
	object Decoderstatus { get; set; }
	object Currentcompressedbitratedecoder_16 { get; set; }
	object Currentcompressedbitratedecoder { get; set; }
	object Progressionorder_17 { get; set; }
	object Progressionorder { get; set; }
	object Codeblockwidth_18 { get; set; }
	object Codeblockwidth { get; set; }
	object Codeblockheight_19 { get; set; }
	object Codeblockheight { get; set; }
	object Fixedzero__fixed { get; set; }
	object Fixedone__fixed { get; set; }
	object Fixedfive__fixed { get; set; }
	object Status_110 { get; set; }
	object Autochromaweight_112 { get; set; }
	object Chromaweight_113 { get; set; }
	object Decoderstatus_115 { get; set; }
	object Progressionorder_117 { get; set; }
	WriteParameters Write { get; set; }
}
public class ConcreteSLProtocolExt : ConcreteSLProtocol, SLProtocolExt
{
	/// <summary>PID: 2  | Type: dummy</summary>
	public System.Object Afterstartup_dummy {get { return GetParameter(2); }set { SetParameter(2, value); }}
	/// <summary>PID: 10  | Type: read | DISCREETS: Disabled = 0, Enabled = 1 | EXCEPTIONS: N/A = 0</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Status_10 {get { return GetParameter(10); }set { SetParameter(10, value); }}
	/// <summary>PID: 10  | Type: read | DISCREETS: Disabled = 0, Enabled = 1 | EXCEPTIONS: N/A = 0</summary>
	public System.Object Status {get { return GetParameter(10); }set { SetParameter(10, value); }}
	/// <summary>PID: 11  | Type: read | DISCREETS: N/A = 0, 128 Mpbs = 1 | EXCEPTIONS: N/A = 0</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Currentcompressedbitrateencoder_11 {get { return GetParameter(11); }set { SetParameter(11, value); }}
	/// <summary>PID: 11  | Type: read | DISCREETS: N/A = 0, 128 Mpbs = 1 | EXCEPTIONS: N/A = 0</summary>
	public System.Object Currentcompressedbitrateencoder {get { return GetParameter(11); }set { SetParameter(11, value); }}
	/// <summary>PID: 12  | Type: read | DISCREETS: N/A = 0, Enabled = 1 | EXCEPTIONS: N/A = 0</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Autochromaweight_12 {get { return GetParameter(12); }set { SetParameter(12, value); }}
	/// <summary>PID: 12  | Type: read | DISCREETS: N/A = 0, Enabled = 1 | EXCEPTIONS: N/A = 0</summary>
	public System.Object Autochromaweight {get { return GetParameter(12); }set { SetParameter(12, value); }}
	/// <summary>PID: 13  | Type: read | DISCREETS: N/A = 0, 24 = 1 | EXCEPTIONS: N/A = 0</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Chromaweight_13 {get { return GetParameter(13); }set { SetParameter(13, value); }}
	/// <summary>PID: 13  | Type: read | DISCREETS: N/A = 0, 24 = 1 | EXCEPTIONS: N/A = 0</summary>
	public System.Object Chromaweight {get { return GetParameter(13); }set { SetParameter(13, value); }}
	/// <summary>PID: 14  | Type: read | DISCREETS: N/A = 0, Enabled = 1 | EXCEPTIONS: N/A = 0</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Losslessmode_14 {get { return GetParameter(14); }set { SetParameter(14, value); }}
	/// <summary>PID: 14  | Type: read | DISCREETS: N/A = 0, Enabled = 1 | EXCEPTIONS: N/A = 0</summary>
	public System.Object Losslessmode {get { return GetParameter(14); }set { SetParameter(14, value); }}
	/// <summary>PID: 15  | Type: read | DISCREETS: Disabled = 0, Enabled = 1 | EXCEPTIONS: N/A = 0</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Decoderstatus_15 {get { return GetParameter(15); }set { SetParameter(15, value); }}
	/// <summary>PID: 15  | Type: read | DISCREETS: Disabled = 0, Enabled = 1 | EXCEPTIONS: N/A = 0</summary>
	public System.Object Decoderstatus {get { return GetParameter(15); }set { SetParameter(15, value); }}
	/// <summary>PID: 16  | Type: read | DISCREETS: N/A = 0, 128 Mpbs = 1 | EXCEPTIONS: N/A = 0</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Currentcompressedbitratedecoder_16 {get { return GetParameter(16); }set { SetParameter(16, value); }}
	/// <summary>PID: 16  | Type: read | DISCREETS: N/A = 0, 128 Mpbs = 1 | EXCEPTIONS: N/A = 0</summary>
	public System.Object Currentcompressedbitratedecoder {get { return GetParameter(16); }set { SetParameter(16, value); }}
	/// <summary>PID: 17  | Type: read | DISCREETS: LCRP = 0, RLCP = 1, RPCL = 2, PCRL = 3, CPRL = 4,  = 5 | EXCEPTIONS: N/A = 5</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Progressionorder_17 {get { return GetParameter(17); }set { SetParameter(17, value); }}
	/// <summary>PID: 17  | Type: read | DISCREETS: LCRP = 0, RLCP = 1, RPCL = 2, PCRL = 3, CPRL = 4,  = 5 | EXCEPTIONS: N/A = 5</summary>
	public System.Object Progressionorder {get { return GetParameter(17); }set { SetParameter(17, value); }}
	/// <summary>PID: 18  | Type: read | DISCREETS: N/A = 0, 512 px = 1 | EXCEPTIONS: N/A = 0</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Codeblockwidth_18 {get { return GetParameter(18); }set { SetParameter(18, value); }}
	/// <summary>PID: 18  | Type: read | DISCREETS: N/A = 0, 512 px = 1 | EXCEPTIONS: N/A = 0</summary>
	public System.Object Codeblockwidth {get { return GetParameter(18); }set { SetParameter(18, value); }}
	/// <summary>PID: 19  | Type: read | DISCREETS: N/A = 0, 512 px = 1 | EXCEPTIONS: N/A = 0</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Codeblockheight_19 {get { return GetParameter(19); }set { SetParameter(19, value); }}
	/// <summary>PID: 19  | Type: read | DISCREETS: N/A = 0, 512 px = 1 | EXCEPTIONS: N/A = 0</summary>
	public System.Object Codeblockheight {get { return GetParameter(19); }set { SetParameter(19, value); }}
	/// <summary>PID: 20  | Type: fixed</summary>
	public System.Object Fixedzero__fixed {get { return GetParameter(20); }set { SetParameter(20, value); }}
	/// <summary>PID: 21  | Type: fixed</summary>
	public System.Object Fixedone__fixed {get { return GetParameter(21); }set { SetParameter(21, value); }}
	/// <summary>PID: 22  | Type: fixed</summary>
	public System.Object Fixedfive__fixed {get { return GetParameter(22); }set { SetParameter(22, value); }}
	/// <summary>PID: 110  | Type: write | DISCREETS: N/A = 0, Enabled = 1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Status_110 {get { return GetParameter(110); }set { SetParameter(110, value); }}
	/// <summary>PID: 112  | Type: write | DISCREETS: N/A = 0, Enabled = 1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Autochromaweight_112 {get { return GetParameter(112); }set { SetParameter(112, value); }}
	/// <summary>PID: 113  | Type: write</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Chromaweight_113 {get { return GetParameter(113); }set { SetParameter(113, value); }}
	/// <summary>PID: 115  | Type: write | DISCREETS: N/A = 0, Enabled = 1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Decoderstatus_115 {get { return GetParameter(115); }set { SetParameter(115, value); }}
	/// <summary>PID: 117  | Type: write | DISCREETS: LCRP = 0, RLCP = 1, RPCL = 2, PCRL = 3, CPRL = 4</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Progressionorder_117 {get { return GetParameter(117); }set { SetParameter(117, value); }}
	public WriteParameters Write { get; set; }
	public ConcreteSLProtocolExt()
	{
		Write = new WriteParameters(this);
	}
}
}
